#!/bin/bash
# this script is used for sign name, default for README.md, optional for first input
# 用来对md文件进行签名和打时间标 
# Liang 2019-03-14
if [ $1 ] ; then
	file=$1
else
	file="/Users/liang/Documents/GitHub/wangliangster.github.io/idea/README.md"
fi

echo '<div style="text-align: right">' >> $file 
echo ' <font size="3" color="blue">' >> $file
echo '   <i>'>> $file
echo '      --- Wang Liang' `date "+ %Y-%b-%d"` >>$file
echo '   </i>'>> $file
echo ' </font>'>> $file	
echo '</div>' >>$file
